#!/bin/zsh



###### Immediatley step on the gas #######

wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" > /etc/apt/sources.list.d/PostgreSQL.list'
apt update 
apt -y upgrade
apt -y install apache2 php7.2 php-mbstring php-curl php-tokenizer php-xmlrpc php-soap php-zip php-gd php-xml php-pgsql postgresql-10
mkdir -p /var/www/{backups,vhosts/trial.com/{httpdocs,logs,moodledata}}
git clone -b MOODLE_36_STABLE git://git.moodle.org/moodle.git /var/www/vhosts/trial.com/httpdocs/
touch /etc/apache2/sites-available/trial.com.conf
cat >/etc/apache2/sites-available/trial.com.conf <<EOL
<VirtualHost *:80>
ServerName trial.com
ServerAlias trial.com

ServerAdmin root@localhost.com
DocumentRoot /var/www/vhosts/trial.com/httpdocs

ErrorLog /var/www/vhosts/trial.com/logs/error.log
CustomLog /var/www/vhosts/trial.com/logs/access.log combined


</VirtualHost>
EOL
cat >/var/www/vhosts/trial.com/httpdocs/config.php <<EOL
<?php  // Moodle configuration file

unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

\$CFG->dbtype    = 'pgsql';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = 'localhost';
\$CFG->dbname    = 'trial';
\$CFG->dbuser    = 'trial';
\$CFG->dbpass    = 'SuperSecretPassword123';
\$CFG->prefix    = 'mdl_';
\$CFG->dboptions = array (
  'dbpersist' => 0,
  'dbport' => '',
  'dbsocket' => '',
);

\$CFG->wwwroot   = 'http://trial.com';
\$CFG->dataroot  = '/var/www/vhosts/trial.com/moodledata';
\$CFG->admin     = 'admin';

\$CFG->directorypermissions = 0777;

require_once(__DIR__ . '/lib/setup.php');

// There is no php closing tag in this file,
// it is intentional because it prevents trailing whitespace problems!
EOL
cat >/tmp/user.sql <<EOL
CREATE USER trial WITH PASSWORD 'SuperSecretPassword123';
CREATE DATABASE trial OWNER trial; 
EOL
sudo -u postgres psql < /tmp/user.sql
chown -R www-data: /var/www/vhosts/trial.com/
chmod -R 775 /var/www/vhosts/trial.com/
a2ensite trial.com
systemctl restart apache2
ufw allow http
sudo -u www-data php /var/www/vhosts/trial.com/httpdocs/admin/cli/install_database.php --agree-license --adminuser=admin --adminpass=supersecretpassworD!23 --adminemail=someone@live.co.uk
rm /tmp/user.sql
